Sample.Core/Models/ErrorViewModel.cs
using System;

namespace Sample.Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sample.Core/Models/Student.cs
using MongoRedi.Attributes;
using MongoRedi.Models;

namespace Sample.Core.Models
{
    [CollectionName("students")]
    [CacheCollection]
    public class Student : BaseCollection
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
    }
}

Sample.Core/Controllers/AsyncController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using MongoRedi.Interfaces;
using Sample.Core.Models;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Sample.Core.Controllers
{
    public class AsyncController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMongoDBRepository<Student> _studentRepository;


        public AsyncController(
            ILogger<HomeController> logger,
            IMongoDBRepository<Student> studentRepository
            )
        {
            _logger = logger;
            _studentRepository = studentRepository;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = await _studentRepository.GetAllAsync();

            return View(viewModel);
        }

        public async Task<IActionResult> UpsertStudent(Student student)
        {
            var existingStudentId = Request.Form["Id"].ToString();

            if (!string.IsNullOrEmpty(existingStudentId))
            {
                student.Id = ObjectId.Parse(existingStudentId);
                await _studentRepository.UpdateAsync(student.Id, student);
            }
            else
            {
                await _studentRepository.InsertAsync(student);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteStudent(string id)
        {
            await _studentRepository.DeleteAsync(id);

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sample.Core/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using MongoRedi.Interfaces;
using Sample.Core.Models;

namespace Sample.Core.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMongoDBRepository<Student> _studentRepository;


        public HomeController(
            ILogger<HomeController> logger,
            IMongoDBRepository<Student> studentRepository
            )
        {
            _logger = logger;
            _studentRepository = studentRepository;
        }

        public IActionResult Index()
        {
            var viewModel = _studentRepository.GetAll();

            return View(viewModel);
        }

        public IActionResult UpsertStudent(Student student)
        {
            var existingStudentId = Request.Form["Id"].ToString();

            if (!string.IsNullOrEmpty(existingStudentId))
            {
                student.Id = ObjectId.Parse(existingStudentId);
                _studentRepository.Update(student.Id, student);
            }
            else
            {
                _studentRepository.Insert(student);
            }

            return RedirectToAction("Index");
        }

        public IActionResult DeleteStudent(string id)
        {
            _studentRepository.Delete(id);

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sample.Core/Views/Async/Index.cshtml
@model IEnumerable<Sample.Core.Models.Student>

<div class="row">
    <div class="col-md-6">
        <h2>Students - ASYNC</h2>
    </div>
    <div class="col-md-6">
        <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target=".addStudent">
            Add Student
        </button>

        <div class="modal addStudent" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <form asp-controller="Async" asp-action="UpsertStudent" method="post">
                        <div class="modal-header">
                            <h5 class="modal-title">Add Student</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label>First Name</label>
                                <input class="form-control" name="FirstName">
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input class="form-control" name="LastName">
                            </div>
                            <div class="form-group">
                                <label>Age</label>
                                <input class="form-control" name="Age">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="50">&nbsp;</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th width="50">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model)
            {
                <tr>
                    <td>
                        <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#edit@(student.Id)">
                            Edit
                        </button>

                        <div id="edit@(student.Id)" class="modal" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <form asp-controller="Async" asp-action="UpsertStudent" method="post">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Edit Student</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" name="Id" value="@(student.Id)" />
                                            <div class="form-group">
                                                <label>First Name</label>
                                                <input class="form-control" name="FirstName" value="@(student.FirstName)">
                                            </div>
                                            <div class="form-group">
                                                <label>Last Name</label>
                                                <input class="form-control" name="LastName" value="@(student.LastName)">
                                            </div>
                                            <div class="form-group">
                                                <label>Age</label>
                                                <input class="form-control" name="Age" value="@(student.Age)">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>@student.FirstName</td>
                    <td>@student.LastName</td>
                    <td>@student.Age</td>
                    <td>
                        <a asp-controller="Async" asp-action="DeleteStudent" asp-route-id="@(student.Id)" class="btn btn-danger confirm">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">
        <strong>
            No students exist
        </strong>
    </div>
}

Sample.Core/Views/Home/Index.cshtml
@model IEnumerable<Sample.Core.Models.Student>

<div class="row">
    <div class="col-md-6">
        <h2>Students</h2>
    </div>
    <div class="col-md-6">
        <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target=".addStudent">
            Add Student
        </button>

        <div class="modal addStudent" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <form asp-controller="Home" asp-action="UpsertStudent" method="post">
                        <div class="modal-header">
                            <h5 class="modal-title">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label>First Name</label>
                                <input class="form-control" name="FirstName">
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input class="form-control" name="LastName">
                            </div>
                            <div class="form-group">
                                <label>Age</label>
                                <input class="form-control" name="Age">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="50">&nbsp;</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th width="50">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model)
            {
                <tr>
                    <td>
                        <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#edit@(student.Id)">
                            Edit
                        </button>

                        <div id="edit@(student.Id)" class="modal" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <form asp-controller="Home" asp-action="UpsertStudent" method="post">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Modal title</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" name="Id" value="@(student.Id)" />
                                            <div class="form-group">
                                                <label>First Name</label>
                                                <input class="form-control" name="FirstName" value="@(student.FirstName)">
                                            </div>
                                            <div class="form-group">
                                                <label>Last Name</label>
                                                <input class="form-control" name="LastName" value="@(student.LastName)">
                                            </div>
                                            <div class="form-group">
                                                <label>Age</label>
                                                <input class="form-control" name="Age" value="@(student.Age)">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>@student.FirstName</td>
                    <td>@student.LastName</td>
                    <td>@student.Age</td>
                    <td>
                        <a asp-controller="Home" asp-action="DeleteStudent" asp-route-id="@(student.Id)" class="btn btn-danger confirm">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">
        <strong>
            No students exist
        </strong>
    </div>
}

Sample.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MongoRedi Sample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MongoRedi Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Home")">SYNC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Async")">ASYNC</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - MongoRedi Sample
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>